// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOyAzTn6VnOgEVLtyjroS3X-fEgEn5BvY',
    appId: '1:501598751191:web:5b0affbf1f0a6a85f02392',
    messagingSenderId: '501598751191',
    projectId: 'rohy-60d0d',
    authDomain: 'rohy-60d0d.firebaseapp.com',
    storageBucket: 'rohy-60d0d.appspot.com',
    measurementId: 'G-E8Q9KSPT8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPTKez1Mx68JyjtnA-1rPlqoJg9V6KpEM',
    appId: '1:501598751191:android:789800f2403a32a8f02392',
    messagingSenderId: '501598751191',
    projectId: 'rohy-60d0d',
    storageBucket: 'rohy-60d0d.appspot.com',
  );
}
